### ISSUE TITLE
Publish runtime/Python3/ on the Python Cheesehop?

### ISSUE THREAD

**Issue by haypo** [antlr/antlr3#179]
Hi,

You publish runtime/Python/ as antlr_python_runtime on the Pyton Cheeseshop (PyPI), but not runtime/Python3/. Would it be possible to publish it? For example as antlr_python3_runtime.

It would help to port the OpenStack Congress project to Python 3.

**Comment by ericvergnaud** [comment]
Hi,
antlr has moved to version 4, for which exists a python 3 runtime in pypi.
not sure there is anybody to maintaining version 3.
I would suggest porting the above project to antlr 4.
Eric

**Comment by haypo** [comment]
Ok, it's fine. Thanks for the reply :-) (Sorry for my late reaction, but I gave up on trying to port Congress to Python 3.)
